version: '3.7'

services:
    composer:
        image: composer:latest
        volumes:
            - .:/app
        working_dir: /app
        command: ["composer", "install"]
    slim:
        image: php:8-alpine
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        environment:
            docker: "true"
        ports:
            - "8080:8080"
        volumes:
            - .:/var/www
            - logs:/var/www/logs
        depends_on:
            - composer
            - db
    db:
        image: percona/percona-server:8.0.35-aarch64  #  ARM64
        #image: percona/percona-server:8.0.35 # x86
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: lab
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
        volumes:
            - db_data:/var/lib/mysql
    phpmyadmin:
        image: arm64v8/phpmyadmin #ARM64
        #image: phpmyadmin/phpmyadmin #x86
        environment:
            PMA_HOST: db
            PMA_USER: admin
            PMA_PASSWORD: admin
        ports:
            - "8081:80"
        depends_on:
            - db

volumes:
    logs:
        driver: local
    db_data:
        driver: local