version: '3.7'

services:
    composer:
        image: composer:latest
        volumes:
            - .:/app
        working_dir: /app
        command: ["composer", "install"]
    web:
        image: php:8-alpine
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        environment:
            docker: "true"
        ports:
            - "8080:8080"
        volumes:
            - .:/var/www
            - logs:/var/www/logs
        depends_on:
            - composer
            - db
    db:
        image: percona/percona-server:8.0.35-aarch64  #  ARM64
        #image: percona/percona-server:8.0.35 # x86
        command: 
            --default-authentication-plugin=caching_sha2_password 
            --early-plugin-load=keyring_file.so 
            --keyring_file_data=/var/lib/mysql-keyring/keyring
            --default-table-encryption=ON
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: MadTestLab
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./keyring:/var/lib/mysql-keyring
    phpmyadmin:
        image: arm64v8/phpmyadmin #ARM64
        #image: phpmyadmin/phpmyadmin #x86
        environment:
            PMA_HOST: db
        ports:
            - "8081:80"
        depends_on:
            - db

volumes:
    logs:
        driver: local