version: '3.8'

services:
  web:
    image: app-name:latest
    build:
      target: web
      context: .
    env_file:
      - .env
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
  
  mysql:
    image: percona/percona-server:8.0.35-aarch64  #  ARM64
    #image: percona/percona-server:8.0.35 # x86
    env_file:
      - .env
    command: 
        --default-authentication-plugin=caching_sha2_password 
        --early-plugin-load=keyring_file.so 
        --keyring_file_data=/var/lib/mysql-keyring/keyring
        --default-table-encryption=ON
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    ports:
      - "3306:3306"
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        - ./keyring:/var/lib/mysql-keyring
  phpmyadmin:
      image: arm64v8/phpmyadmin #ARM64
      #image: phpmyadmin/phpmyadmin #x86
      environment:
          PMA_HOST: mysql
      ports:
          - "8081:80"
      depends_on:
          - mysql